
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 29 2023 12:58:15 IST (Nov 29 2023 07:28:15 UTC)

// Verification Directory fv/mac 

module add_unsigned(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_98, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_294, n_295, n_296, n_297, n_298;
  wire n_299, n_300, n_301, n_302, n_303, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315, n_316, n_317, n_318, n_319, n_320, n_321, n_322;
  wire n_323, n_324, n_329, n_330, n_331, n_332, n_333, n_334;
  wire n_335, n_336, n_337, n_338, n_339, n_340, n_341, n_342;
  wire n_343, n_344, n_345, n_346, n_347, n_348, n_349, n_350;
  wire n_351, n_352, n_353, n_354, n_355, n_356, n_357, n_358;
  wire n_359, n_360, n_361, n_362, n_363, n_364, n_365, n_366;
  wire n_367, n_368, n_369, n_370, n_371, n_372, n_373, n_374;
  wire n_375, n_376, n_377, n_378, n_379, n_380, n_381, n_387;
  wire n_388, n_389, n_390, n_391, n_392, n_393, n_394, n_395;
  wire n_396, n_397, n_398, n_399, n_400, n_401, n_402, n_403;
  wire n_404, n_405, n_406, n_407, n_408, n_409, n_410, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_428, n_429, n_430, n_431, n_432, n_433, n_434, n_439;
  wire n_440, n_441, n_442, n_443, n_444, n_445, n_446, n_447;
  wire n_448, n_449, n_450, n_451, n_452, n_453, n_454, n_455;
  wire n_456, n_457, n_458, n_459, n_460, n_461, n_462, n_463;
  wire n_464, n_465, n_466, n_467, n_468, n_469, n_470, n_471;
  wire n_472, n_473, n_474, n_475, n_476, n_477, n_478, n_479;
  wire n_480, n_481, n_482, n_483, n_484, n_485, n_486, n_487;
  wire n_488, n_489, n_490, n_491, n_492, n_493, n_494, n_495;
  wire n_496, n_497, n_498, n_499, n_500, n_501, n_502, n_503;
  wire n_504, n_505, n_506, n_507, n_508, n_509, n_510, n_511;
  wire n_512, n_513;
  xor g1 (Z[0], A[0], B[0]);
  nand g2 (n_98, A[0], B[0]);
  nor g6 (n_101, A[1], B[1]);
  nand g7 (n_104, A[1], B[1]);
  nor g8 (n_111, A[2], B[2]);
  nand g9 (n_106, A[2], B[2]);
  nor g10 (n_107, A[3], B[3]);
  nand g11 (n_108, A[3], B[3]);
  nor g12 (n_117, A[4], B[4]);
  nand g13 (n_112, A[4], B[4]);
  nor g14 (n_113, A[5], B[5]);
  nand g15 (n_114, A[5], B[5]);
  nor g16 (n_123, A[6], B[6]);
  nand g17 (n_118, A[6], B[6]);
  nor g18 (n_119, A[7], B[7]);
  nand g19 (n_120, A[7], B[7]);
  nor g20 (n_129, A[8], B[8]);
  nand g21 (n_124, A[8], B[8]);
  nor g22 (n_125, A[9], B[9]);
  nand g23 (n_126, A[9], B[9]);
  nor g24 (n_135, A[10], B[10]);
  nand g25 (n_130, A[10], B[10]);
  nor g26 (n_131, A[11], B[11]);
  nand g27 (n_132, A[11], B[11]);
  nor g28 (n_141, A[12], B[12]);
  nand g29 (n_136, A[12], B[12]);
  nor g30 (n_137, A[13], B[13]);
  nand g31 (n_138, A[13], B[13]);
  nor g32 (n_147, A[14], B[14]);
  nand g33 (n_142, A[14], B[14]);
  nor g34 (n_143, A[15], B[15]);
  nand g35 (n_144, A[15], B[15]);
  nor g36 (n_153, A[16], B[16]);
  nand g37 (n_148, A[16], B[16]);
  nor g38 (n_149, A[17], B[17]);
  nand g39 (n_150, A[17], B[17]);
  nor g40 (n_159, A[18], B[18]);
  nand g41 (n_154, A[18], B[18]);
  nor g42 (n_155, A[19], B[19]);
  nand g43 (n_156, A[19], B[19]);
  nor g44 (n_165, A[20], B[20]);
  nand g45 (n_160, A[20], B[20]);
  nor g46 (n_161, A[21], B[21]);
  nand g47 (n_162, A[21], B[21]);
  nor g48 (n_171, A[22], B[22]);
  nand g49 (n_166, A[22], B[22]);
  nor g50 (n_167, A[23], B[23]);
  nand g51 (n_168, A[23], B[23]);
  nor g52 (n_177, A[24], B[24]);
  nand g53 (n_172, A[24], B[24]);
  nor g54 (n_173, A[25], B[25]);
  nand g55 (n_174, A[25], B[25]);
  nor g56 (n_183, A[26], B[26]);
  nand g57 (n_178, A[26], B[26]);
  nor g58 (n_179, A[27], B[27]);
  nand g59 (n_180, A[27], B[27]);
  nor g60 (n_189, A[28], B[28]);
  nand g61 (n_184, A[28], B[28]);
  nor g62 (n_185, A[29], B[29]);
  nand g63 (n_186, A[29], B[29]);
  nor g64 (n_195, A[30], B[30]);
  nand g65 (n_190, A[30], B[30]);
  nor g66 (n_191, A[31], B[31]);
  nand g67 (n_192, A[31], B[31]);
  not g68 (n_103, n_101);
  nand g69 (n_105, n_102, n_103);
  nand g70 (n_196, n_104, n_105);
  nor g71 (n_109, n_106, n_107);
  not g72 (n_110, n_108);
  nor g73 (n_200, n_109, n_110);
  nor g74 (n_199, n_111, n_107);
  nor g75 (n_115, n_112, n_113);
  not g76 (n_116, n_114);
  nor g77 (n_202, n_115, n_116);
  nor g78 (n_205, n_117, n_113);
  nor g79 (n_121, n_118, n_119);
  not g80 (n_122, n_120);
  nor g81 (n_209, n_121, n_122);
  nor g82 (n_207, n_123, n_119);
  nor g83 (n_127, n_124, n_125);
  not g84 (n_128, n_126);
  nor g85 (n_212, n_127, n_128);
  nor g86 (n_215, n_129, n_125);
  nor g87 (n_133, n_130, n_131);
  not g88 (n_134, n_132);
  nor g89 (n_219, n_133, n_134);
  nor g90 (n_217, n_135, n_131);
  nor g91 (n_139, n_136, n_137);
  not g92 (n_140, n_138);
  nor g93 (n_222, n_139, n_140);
  nor g94 (n_225, n_141, n_137);
  nor g95 (n_145, n_142, n_143);
  not g96 (n_146, n_144);
  nor g97 (n_229, n_145, n_146);
  nor g98 (n_227, n_147, n_143);
  nor g99 (n_151, n_148, n_149);
  not g100 (n_152, n_150);
  nor g101 (n_232, n_151, n_152);
  nor g102 (n_235, n_153, n_149);
  nor g103 (n_157, n_154, n_155);
  not g104 (n_158, n_156);
  nor g105 (n_239, n_157, n_158);
  nor g106 (n_237, n_159, n_155);
  nor g107 (n_163, n_160, n_161);
  not g108 (n_164, n_162);
  nor g109 (n_242, n_163, n_164);
  nor g110 (n_245, n_165, n_161);
  nor g111 (n_169, n_166, n_167);
  not g112 (n_170, n_168);
  nor g113 (n_249, n_169, n_170);
  nor g114 (n_247, n_171, n_167);
  nor g115 (n_175, n_172, n_173);
  not g116 (n_176, n_174);
  nor g117 (n_252, n_175, n_176);
  nor g118 (n_255, n_177, n_173);
  nor g119 (n_181, n_178, n_179);
  not g120 (n_182, n_180);
  nor g121 (n_259, n_181, n_182);
  nor g122 (n_257, n_183, n_179);
  nor g123 (n_187, n_184, n_185);
  not g124 (n_188, n_186);
  nor g125 (n_262, n_187, n_188);
  nor g126 (n_265, n_189, n_185);
  not g131 (n_197, n_111);
  nand g132 (n_198, n_196, n_197);
  nand g133 (n_442, n_106, n_198);
  nand g134 (n_201, n_199, n_196);
  nand g135 (n_272, n_200, n_201);
  nor g136 (n_203, n_123, n_202);
  not g137 (n_204, n_118);
  nor g138 (n_278, n_203, n_204);
  not g139 (n_206, n_123);
  nand g140 (n_276, n_205, n_206);
  not g141 (n_208, n_207);
  nor g142 (n_210, n_202, n_208);
  not g143 (n_211, n_209);
  nor g144 (n_282, n_210, n_211);
  nand g145 (n_280, n_205, n_207);
  nor g146 (n_213, n_135, n_212);
  not g147 (n_214, n_130);
  nor g148 (n_335, n_213, n_214);
  not g149 (n_216, n_135);
  nand g150 (n_333, n_215, n_216);
  not g151 (n_218, n_217);
  nor g152 (n_220, n_212, n_218);
  not g153 (n_221, n_219);
  nor g154 (n_284, n_220, n_221);
  nand g155 (n_287, n_215, n_217);
  nor g156 (n_223, n_147, n_222);
  not g157 (n_224, n_142);
  nor g158 (n_292, n_223, n_224);
  not g159 (n_226, n_147);
  nand g160 (n_291, n_225, n_226);
  not g161 (n_228, n_227);
  nor g162 (n_230, n_222, n_228);
  not g163 (n_231, n_229);
  nor g164 (n_296, n_230, n_231);
  nand g165 (n_295, n_225, n_227);
  nor g166 (n_233, n_159, n_232);
  not g167 (n_234, n_154);
  nor g168 (n_393, n_233, n_234);
  not g169 (n_236, n_159);
  nand g170 (n_391, n_235, n_236);
  not g171 (n_238, n_237);
  nor g172 (n_240, n_232, n_238);
  not g173 (n_241, n_239);
  nor g174 (n_299, n_240, n_241);
  nand g175 (n_302, n_235, n_237);
  nor g176 (n_243, n_171, n_242);
  not g177 (n_244, n_166);
  nor g178 (n_307, n_243, n_244);
  not g179 (n_246, n_171);
  nand g180 (n_306, n_245, n_246);
  not g181 (n_248, n_247);
  nor g182 (n_250, n_242, n_248);
  not g183 (n_251, n_249);
  nor g184 (n_311, n_250, n_251);
  nand g185 (n_310, n_245, n_247);
  nor g186 (n_253, n_183, n_252);
  not g187 (n_254, n_178);
  nor g188 (n_360, n_253, n_254);
  not g189 (n_256, n_183);
  nand g190 (n_359, n_255, n_256);
  not g191 (n_258, n_257);
  nor g192 (n_260, n_252, n_258);
  not g193 (n_261, n_259);
  nor g194 (n_314, n_260, n_261);
  nand g195 (n_317, n_255, n_257);
  nor g196 (n_263, n_195, n_262);
  not g197 (n_264, n_190);
  nor g198 (n_322, n_263, n_264);
  not g199 (n_266, n_195);
  nand g200 (n_321, n_265, n_266);
  not g206 (n_273, n_117);
  nand g207 (n_274, n_272, n_273);
  nand g208 (n_446, n_112, n_274);
  nand g209 (n_275, n_205, n_272);
  nand g210 (n_448, n_202, n_275);
  not g211 (n_277, n_276);
  nand g212 (n_279, n_272, n_277);
  nand g213 (n_451, n_278, n_279);
  not g214 (n_281, n_280);
  nand g215 (n_283, n_272, n_281);
  nand g216 (n_329, n_282, n_283);
  nor g217 (n_285, n_141, n_284);
  not g218 (n_286, n_136);
  nor g219 (n_340, n_285, n_286);
  nor g220 (n_339, n_141, n_287);
  not g221 (n_288, n_225);
  nor g222 (n_289, n_284, n_288);
  not g223 (n_290, n_222);
  nor g224 (n_343, n_289, n_290);
  nor g225 (n_342, n_287, n_288);
  nor g226 (n_293, n_291, n_284);
  not g227 (n_294, n_292);
  nor g228 (n_346, n_293, n_294);
  nor g229 (n_345, n_287, n_291);
  nor g230 (n_297, n_295, n_284);
  not g231 (n_298, n_296);
  nor g232 (n_349, n_297, n_298);
  nor g233 (n_348, n_287, n_295);
  nor g234 (n_300, n_165, n_299);
  not g235 (n_301, n_160);
  nor g236 (n_398, n_300, n_301);
  nor g237 (n_397, n_165, n_302);
  not g238 (n_303, n_245);
  nor g239 (n_304, n_299, n_303);
  not g240 (n_305, n_242);
  nor g241 (n_401, n_304, n_305);
  nor g242 (n_400, n_302, n_303);
  nor g243 (n_308, n_306, n_299);
  not g244 (n_309, n_307);
  nor g245 (n_404, n_308, n_309);
  nor g246 (n_403, n_302, n_306);
  nor g247 (n_312, n_310, n_299);
  not g248 (n_313, n_311);
  nor g249 (n_351, n_312, n_313);
  nor g250 (n_354, n_302, n_310);
  nor g251 (n_315, n_189, n_314);
  not g252 (n_316, n_184);
  nor g253 (n_369, n_315, n_316);
  nor g254 (n_367, n_189, n_317);
  not g255 (n_318, n_265);
  nor g256 (n_319, n_314, n_318);
  not g257 (n_320, n_262);
  nor g258 (n_374, n_319, n_320);
  nor g259 (n_372, n_317, n_318);
  nor g260 (n_323, n_321, n_314);
  not g261 (n_324, n_322);
  nor g262 (n_379, n_323, n_324);
  nor g263 (n_377, n_317, n_321);
  not g268 (n_330, n_129);
  nand g269 (n_331, n_329, n_330);
  nand g270 (n_455, n_124, n_331);
  nand g271 (n_332, n_215, n_329);
  nand g272 (n_457, n_212, n_332);
  not g273 (n_334, n_333);
  nand g274 (n_336, n_329, n_334);
  nand g275 (n_460, n_335, n_336);
  not g276 (n_337, n_287);
  nand g277 (n_338, n_329, n_337);
  nand g278 (n_463, n_284, n_338);
  nand g279 (n_341, n_339, n_329);
  nand g280 (n_466, n_340, n_341);
  nand g281 (n_344, n_342, n_329);
  nand g282 (n_468, n_343, n_344);
  nand g283 (n_347, n_345, n_329);
  nand g284 (n_471, n_346, n_347);
  nand g285 (n_350, n_348, n_329);
  nand g286 (n_387, n_349, n_350);
  nor g287 (n_352, n_177, n_351);
  not g288 (n_353, n_172);
  nor g289 (n_409, n_352, n_353);
  not g290 (n_355, n_177);
  nand g291 (n_407, n_354, n_355);
  not g292 (n_356, n_255);
  nor g293 (n_357, n_351, n_356);
  not g294 (n_358, n_252);
  nor g295 (n_413, n_357, n_358);
  nand g296 (n_411, n_255, n_354);
  nor g297 (n_361, n_359, n_351);
  not g298 (n_362, n_360);
  nor g299 (n_417, n_361, n_362);
  not g300 (n_363, n_359);
  nand g301 (n_415, n_354, n_363);
  nor g302 (n_364, n_317, n_351);
  not g303 (n_365, n_314);
  nor g304 (n_421, n_364, n_365);
  not g305 (n_366, n_317);
  nand g306 (n_419, n_354, n_366);
  not g307 (n_368, n_367);
  nor g308 (n_370, n_351, n_368);
  not g309 (n_371, n_369);
  nor g310 (n_425, n_370, n_371);
  nand g311 (n_423, n_354, n_367);
  not g312 (n_373, n_372);
  nor g313 (n_375, n_351, n_373);
  not g314 (n_376, n_374);
  nor g315 (n_429, n_375, n_376);
  nand g316 (n_427, n_354, n_372);
  not g317 (n_378, n_377);
  nor g318 (n_380, n_351, n_378);
  not g319 (n_381, n_379);
  nor g320 (n_433, n_380, n_381);
  nand g321 (n_431, n_354, n_377);
  not g327 (n_388, n_153);
  nand g328 (n_389, n_387, n_388);
  nand g329 (n_475, n_148, n_389);
  nand g330 (n_390, n_235, n_387);
  nand g331 (n_477, n_232, n_390);
  not g332 (n_392, n_391);
  nand g333 (n_394, n_387, n_392);
  nand g334 (n_480, n_393, n_394);
  not g335 (n_395, n_302);
  nand g336 (n_396, n_387, n_395);
  nand g337 (n_483, n_299, n_396);
  nand g338 (n_399, n_397, n_387);
  nand g339 (n_486, n_398, n_399);
  nand g340 (n_402, n_400, n_387);
  nand g341 (n_488, n_401, n_402);
  nand g342 (n_405, n_403, n_387);
  nand g343 (n_491, n_404, n_405);
  nand g344 (n_406, n_354, n_387);
  nand g345 (n_493, n_351, n_406);
  not g346 (n_408, n_407);
  nand g347 (n_410, n_387, n_408);
  nand g348 (n_496, n_409, n_410);
  not g349 (n_412, n_411);
  nand g350 (n_414, n_387, n_412);
  nand g351 (n_498, n_413, n_414);
  not g352 (n_416, n_415);
  nand g353 (n_418, n_387, n_416);
  nand g354 (n_501, n_417, n_418);
  not g355 (n_420, n_419);
  nand g356 (n_422, n_387, n_420);
  nand g357 (n_504, n_421, n_422);
  not g358 (n_424, n_423);
  nand g359 (n_426, n_387, n_424);
  nand g360 (n_507, n_425, n_426);
  not g361 (n_428, n_427);
  nand g362 (n_430, n_387, n_428);
  nand g363 (n_509, n_429, n_430);
  not g364 (n_432, n_431);
  nand g365 (n_434, n_387, n_432);
  nand g366 (n_512, n_433, n_434);
  nand g370 (n_439, n_103, n_104);
  xnor g371 (Z[1], n_102, n_439);
  nand g372 (n_440, n_197, n_106);
  xnor g373 (Z[2], n_196, n_440);
  not g374 (n_441, n_107);
  nand g375 (n_443, n_441, n_108);
  xnor g376 (Z[3], n_442, n_443);
  nand g377 (n_444, n_273, n_112);
  xnor g378 (Z[4], n_272, n_444);
  not g379 (n_445, n_113);
  nand g380 (n_447, n_445, n_114);
  xnor g381 (Z[5], n_446, n_447);
  nand g382 (n_449, n_206, n_118);
  xnor g383 (Z[6], n_448, n_449);
  not g384 (n_450, n_119);
  nand g385 (n_452, n_450, n_120);
  xnor g386 (Z[7], n_451, n_452);
  nand g387 (n_453, n_330, n_124);
  xnor g388 (Z[8], n_329, n_453);
  not g389 (n_454, n_125);
  nand g390 (n_456, n_454, n_126);
  xnor g391 (Z[9], n_455, n_456);
  nand g392 (n_458, n_216, n_130);
  xnor g393 (Z[10], n_457, n_458);
  not g394 (n_459, n_131);
  nand g395 (n_461, n_459, n_132);
  xnor g396 (Z[11], n_460, n_461);
  not g397 (n_462, n_141);
  nand g398 (n_464, n_462, n_136);
  xnor g399 (Z[12], n_463, n_464);
  not g400 (n_465, n_137);
  nand g401 (n_467, n_465, n_138);
  xnor g402 (Z[13], n_466, n_467);
  nand g403 (n_469, n_226, n_142);
  xnor g404 (Z[14], n_468, n_469);
  not g405 (n_470, n_143);
  nand g406 (n_472, n_470, n_144);
  xnor g407 (Z[15], n_471, n_472);
  nand g408 (n_473, n_388, n_148);
  xnor g409 (Z[16], n_387, n_473);
  not g410 (n_474, n_149);
  nand g411 (n_476, n_474, n_150);
  xnor g412 (Z[17], n_475, n_476);
  nand g413 (n_478, n_236, n_154);
  xnor g414 (Z[18], n_477, n_478);
  not g415 (n_479, n_155);
  nand g416 (n_481, n_479, n_156);
  xnor g417 (Z[19], n_480, n_481);
  not g418 (n_482, n_165);
  nand g419 (n_484, n_482, n_160);
  xnor g420 (Z[20], n_483, n_484);
  not g421 (n_485, n_161);
  nand g422 (n_487, n_485, n_162);
  xnor g423 (Z[21], n_486, n_487);
  nand g424 (n_489, n_246, n_166);
  xnor g425 (Z[22], n_488, n_489);
  not g426 (n_490, n_167);
  nand g427 (n_492, n_490, n_168);
  xnor g428 (Z[23], n_491, n_492);
  nand g429 (n_494, n_355, n_172);
  xnor g430 (Z[24], n_493, n_494);
  not g431 (n_495, n_173);
  nand g432 (n_497, n_495, n_174);
  xnor g433 (Z[25], n_496, n_497);
  nand g434 (n_499, n_256, n_178);
  xnor g435 (Z[26], n_498, n_499);
  not g436 (n_500, n_179);
  nand g437 (n_502, n_500, n_180);
  xnor g438 (Z[27], n_501, n_502);
  not g439 (n_503, n_189);
  nand g440 (n_505, n_503, n_184);
  xnor g441 (Z[28], n_504, n_505);
  not g442 (n_506, n_185);
  nand g443 (n_508, n_506, n_186);
  xnor g444 (Z[29], n_507, n_508);
  nand g445 (n_510, n_266, n_190);
  xnor g446 (Z[30], n_509, n_510);
  not g447 (n_511, n_191);
  nand g448 (n_513, n_511, n_192);
  xnor g449 (Z[31], n_512, n_513);
  not g451 (n_102, n_98);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [15:0] in_0, in_1;
  output [15:0] z;
  wire ctl;
  wire [15:0] in_0, in_1;
  wire [15:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module mac(clk, rst, x, y, acc);
  input clk, rst;
  input [15:0] x, y;
  output [31:0] acc;
  wire clk, rst;
  wire [15:0] x, y;
  wire [31:0] acc;
  wire [15:0] in1;
  wire [15:0] in2;
  wire [31:0] w1;
  wire [31:0] x1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  vm16bit v01(in1, in2, w1);
  pipo p1(acc, clk, rst, x1);
  add_unsigned add_13_14(.A (w1), .B (x1), .Z (acc));
  bmux mux_in2_10_5(.ctl (rst), .in_0 (y), .in_1
       (16'b0000000000000000), .z ({UNCONNECTED14, UNCONNECTED13,
       UNCONNECTED12, UNCONNECTED11, UNCONNECTED10, UNCONNECTED9,
       UNCONNECTED8, UNCONNECTED7, UNCONNECTED6, UNCONNECTED5,
       UNCONNECTED4, UNCONNECTED3, UNCONNECTED2, UNCONNECTED1,
       UNCONNECTED0, UNCONNECTED}));
  bmux mux_in1_10_5(.ctl (rst), .in_0 (x), .in_1
       (16'b0000000000000000), .z ({UNCONNECTED30, UNCONNECTED29,
       UNCONNECTED28, UNCONNECTED27, UNCONNECTED26, UNCONNECTED25,
       UNCONNECTED24, UNCONNECTED23, UNCONNECTED22, UNCONNECTED21,
       UNCONNECTED20, UNCONNECTED19, UNCONNECTED18, UNCONNECTED17,
       UNCONNECTED16, UNCONNECTED15}));
  CDN_flop \in1_reg[0] (.clk (clk), .d (x[0]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[0]));
  CDN_flop \in1_reg[1] (.clk (clk), .d (x[1]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[1]));
  CDN_flop \in1_reg[2] (.clk (clk), .d (x[2]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[2]));
  CDN_flop \in1_reg[3] (.clk (clk), .d (x[3]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[3]));
  CDN_flop \in1_reg[4] (.clk (clk), .d (x[4]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[4]));
  CDN_flop \in1_reg[5] (.clk (clk), .d (x[5]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[5]));
  CDN_flop \in1_reg[6] (.clk (clk), .d (x[6]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[6]));
  CDN_flop \in1_reg[7] (.clk (clk), .d (x[7]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[7]));
  CDN_flop \in1_reg[8] (.clk (clk), .d (x[8]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[8]));
  CDN_flop \in1_reg[9] (.clk (clk), .d (x[9]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[9]));
  CDN_flop \in1_reg[10] (.clk (clk), .d (x[10]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[10]));
  CDN_flop \in1_reg[11] (.clk (clk), .d (x[11]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[11]));
  CDN_flop \in1_reg[12] (.clk (clk), .d (x[12]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[12]));
  CDN_flop \in1_reg[13] (.clk (clk), .d (x[13]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[13]));
  CDN_flop \in1_reg[14] (.clk (clk), .d (x[14]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[14]));
  CDN_flop \in1_reg[15] (.clk (clk), .d (x[15]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in1[15]));
  CDN_flop \in2_reg[0] (.clk (clk), .d (y[0]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[0]));
  CDN_flop \in2_reg[1] (.clk (clk), .d (y[1]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[1]));
  CDN_flop \in2_reg[2] (.clk (clk), .d (y[2]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[2]));
  CDN_flop \in2_reg[3] (.clk (clk), .d (y[3]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[3]));
  CDN_flop \in2_reg[4] (.clk (clk), .d (y[4]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[4]));
  CDN_flop \in2_reg[5] (.clk (clk), .d (y[5]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[5]));
  CDN_flop \in2_reg[6] (.clk (clk), .d (y[6]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[6]));
  CDN_flop \in2_reg[7] (.clk (clk), .d (y[7]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[7]));
  CDN_flop \in2_reg[8] (.clk (clk), .d (y[8]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[8]));
  CDN_flop \in2_reg[9] (.clk (clk), .d (y[9]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[9]));
  CDN_flop \in2_reg[10] (.clk (clk), .d (y[10]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[10]));
  CDN_flop \in2_reg[11] (.clk (clk), .d (y[11]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[11]));
  CDN_flop \in2_reg[12] (.clk (clk), .d (y[12]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[12]));
  CDN_flop \in2_reg[13] (.clk (clk), .d (y[13]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[13]));
  CDN_flop \in2_reg[14] (.clk (clk), .d (y[14]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[14]));
  CDN_flop \in2_reg[15] (.clk (clk), .d (y[15]), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (rst), .srd (1'b0), .q (in2[15]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
