// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov 29 2023 12:58:57 IST (Nov 29 2023 07:28:57 UTC)

// Verification Directory fv/mac 

module mac(clk, rst, x, y, acc);
  input clk, rst;
  input [15:0] x, y;
  output [31:0] acc;
  wire clk, rst;
  wire [15:0] x, y;
  wire [31:0] acc;
  wire [31:0] x1;
  wire [15:0] in1;
  wire [15:0] in2;
  wire [31:0] w1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire add_13_14_n_1335, add_13_14_n_1337, add_13_14_n_1339,
       add_13_14_n_1341, add_13_14_n_1343, add_13_14_n_1345,
       add_13_14_n_1347, add_13_14_n_1349;
  wire add_13_14_n_1351, add_13_14_n_1353, add_13_14_n_1355,
       add_13_14_n_1357, add_13_14_n_1359, add_13_14_n_1361,
       add_13_14_n_1363, add_13_14_n_1365;
  wire add_13_14_n_1367, add_13_14_n_1369, add_13_14_n_1371,
       add_13_14_n_1373, add_13_14_n_1375, add_13_14_n_1377,
       add_13_14_n_1379, add_13_14_n_1381;
  wire add_13_14_n_1383, add_13_14_n_1385, add_13_14_n_1387,
       add_13_14_n_1389, add_13_14_n_1391, add_13_14_n_1393,
       add_13_14_n_1395, n_0;
  pipo p1(acc, clk, rst, x1);
  vm16bit v01(in1, in2, w1);
  DFFTRX2 \in2_reg[1] (.CK (clk), .D (n_0), .RN (y[1]), .Q (in2[1]),
       .QN (UNCONNECTED));
  DFFTRX2 \in1_reg[1] (.CK (clk), .D (n_0), .RN (x[1]), .Q (in1[1]),
       .QN (UNCONNECTED0));
  DFFTRX2 \in1_reg[3] (.CK (clk), .D (n_0), .RN (x[3]), .Q (in1[3]),
       .QN (UNCONNECTED1));
  DFFTRX2 \in1_reg[4] (.CK (clk), .D (n_0), .RN (x[4]), .Q (in1[4]),
       .QN (UNCONNECTED2));
  DFFTRX2 \in1_reg[5] (.CK (clk), .D (n_0), .RN (x[5]), .Q (in1[5]),
       .QN (UNCONNECTED3));
  DFFTRX2 \in1_reg[7] (.CK (clk), .D (n_0), .RN (x[7]), .Q (in1[7]),
       .QN (UNCONNECTED4));
  DFFTRX2 \in1_reg[6] (.CK (clk), .D (n_0), .RN (x[6]), .Q (in1[6]),
       .QN (UNCONNECTED5));
  DFFTRX2 \in1_reg[8] (.CK (clk), .D (n_0), .RN (x[8]), .Q (in1[8]),
       .QN (UNCONNECTED6));
  DFFTRX2 \in1_reg[10] (.CK (clk), .D (n_0), .RN (x[10]), .Q (in1[10]),
       .QN (UNCONNECTED7));
  DFFTRX2 \in1_reg[11] (.CK (clk), .D (n_0), .RN (x[11]), .Q (in1[11]),
       .QN (UNCONNECTED8));
  DFFTRX2 \in1_reg[12] (.CK (clk), .D (n_0), .RN (x[12]), .Q (in1[12]),
       .QN (UNCONNECTED9));
  DFFTRX2 \in1_reg[13] (.CK (clk), .D (n_0), .RN (x[13]), .Q (in1[13]),
       .QN (UNCONNECTED10));
  DFFTRX2 \in1_reg[14] (.CK (clk), .D (n_0), .RN (x[14]), .Q (in1[14]),
       .QN (UNCONNECTED11));
  DFFTRX2 \in1_reg[15] (.CK (clk), .D (n_0), .RN (x[15]), .Q (in1[15]),
       .QN (UNCONNECTED12));
  DFFTRX2 \in2_reg[0] (.CK (clk), .D (n_0), .RN (y[0]), .Q (in2[0]),
       .QN (UNCONNECTED13));
  DFFTRX2 \in1_reg[2] (.CK (clk), .D (n_0), .RN (x[2]), .Q (in1[2]),
       .QN (UNCONNECTED14));
  DFFTRX2 \in1_reg[9] (.CK (clk), .D (n_0), .RN (x[9]), .Q (in1[9]),
       .QN (UNCONNECTED15));
  DFFTRX2 \in2_reg[3] (.CK (clk), .D (n_0), .RN (y[3]), .Q (in2[3]),
       .QN (UNCONNECTED16));
  DFFTRX2 \in2_reg[4] (.CK (clk), .D (n_0), .RN (y[4]), .Q (in2[4]),
       .QN (UNCONNECTED17));
  DFFTRX2 \in2_reg[5] (.CK (clk), .D (n_0), .RN (y[5]), .Q (in2[5]),
       .QN (UNCONNECTED18));
  DFFTRX2 \in1_reg[0] (.CK (clk), .D (n_0), .RN (x[0]), .Q (in1[0]),
       .QN (UNCONNECTED19));
  DFFTRX2 \in2_reg[9] (.CK (clk), .D (n_0), .RN (y[9]), .Q (in2[9]),
       .QN (UNCONNECTED20));
  DFFTRX2 \in2_reg[10] (.CK (clk), .D (n_0), .RN (y[10]), .Q (in2[10]),
       .QN (UNCONNECTED21));
  DFFTRX2 \in2_reg[11] (.CK (clk), .D (n_0), .RN (y[11]), .Q (in2[11]),
       .QN (UNCONNECTED22));
  DFFTRX2 \in2_reg[12] (.CK (clk), .D (n_0), .RN (y[12]), .Q (in2[12]),
       .QN (UNCONNECTED23));
  DFFTRX2 \in2_reg[13] (.CK (clk), .D (n_0), .RN (y[13]), .Q (in2[13]),
       .QN (UNCONNECTED24));
  DFFTRX2 \in2_reg[14] (.CK (clk), .D (n_0), .RN (y[14]), .Q (in2[14]),
       .QN (UNCONNECTED25));
  DFFTRX2 \in2_reg[7] (.CK (clk), .D (n_0), .RN (y[7]), .Q (in2[7]),
       .QN (UNCONNECTED26));
  DFFTRX2 \in2_reg[15] (.CK (clk), .D (n_0), .RN (y[15]), .Q (in2[15]),
       .QN (UNCONNECTED27));
  DFFTRX2 \in2_reg[6] (.CK (clk), .D (n_0), .RN (y[6]), .Q (in2[6]),
       .QN (UNCONNECTED28));
  DFFTRX2 \in2_reg[8] (.CK (clk), .D (n_0), .RN (y[8]), .Q (in2[8]),
       .QN (UNCONNECTED29));
  DFFTRX2 \in2_reg[2] (.CK (clk), .D (n_0), .RN (y[2]), .Q (in2[2]),
       .QN (UNCONNECTED30));
  INVXL g165(.A (rst), .Y (n_0));
  ADDFXL add_13_14_g2876__8780(.A (w1[30]), .B (x1[30]), .CI
       (add_13_14_n_1337), .CO (add_13_14_n_1335), .S (acc[30]));
  ADDFXL add_13_14_g2877__4296(.A (w1[29]), .B (x1[29]), .CI
       (add_13_14_n_1339), .CO (add_13_14_n_1337), .S (acc[29]));
  ADDFXL add_13_14_g2878__3772(.A (w1[28]), .B (x1[28]), .CI
       (add_13_14_n_1341), .CO (add_13_14_n_1339), .S (acc[28]));
  ADDFXL add_13_14_g2879__1474(.A (w1[27]), .B (x1[27]), .CI
       (add_13_14_n_1343), .CO (add_13_14_n_1341), .S (acc[27]));
  ADDFXL add_13_14_g2880__4547(.A (w1[26]), .B (x1[26]), .CI
       (add_13_14_n_1345), .CO (add_13_14_n_1343), .S (acc[26]));
  ADDFXL add_13_14_g2881__9682(.A (w1[25]), .B (x1[25]), .CI
       (add_13_14_n_1347), .CO (add_13_14_n_1345), .S (acc[25]));
  ADDFXL add_13_14_g2882__2683(.A (w1[24]), .B (x1[24]), .CI
       (add_13_14_n_1349), .CO (add_13_14_n_1347), .S (acc[24]));
  ADDFXL add_13_14_g2883__1309(.A (w1[23]), .B (x1[23]), .CI
       (add_13_14_n_1351), .CO (add_13_14_n_1349), .S (acc[23]));
  ADDFXL add_13_14_g2884__6877(.A (w1[22]), .B (x1[22]), .CI
       (add_13_14_n_1353), .CO (add_13_14_n_1351), .S (acc[22]));
  ADDFXL add_13_14_g2885__2900(.A (w1[21]), .B (x1[21]), .CI
       (add_13_14_n_1355), .CO (add_13_14_n_1353), .S (acc[21]));
  ADDFXL add_13_14_g2886__2391(.A (w1[20]), .B (x1[20]), .CI
       (add_13_14_n_1357), .CO (add_13_14_n_1355), .S (acc[20]));
  ADDFXL add_13_14_g2887__7675(.A (w1[19]), .B (x1[19]), .CI
       (add_13_14_n_1359), .CO (add_13_14_n_1357), .S (acc[19]));
  ADDFXL add_13_14_g2888__7118(.A (w1[18]), .B (x1[18]), .CI
       (add_13_14_n_1361), .CO (add_13_14_n_1359), .S (acc[18]));
  ADDFXL add_13_14_g2889__8757(.A (w1[17]), .B (x1[17]), .CI
       (add_13_14_n_1363), .CO (add_13_14_n_1361), .S (acc[17]));
  ADDFXL add_13_14_g2890__1786(.A (w1[16]), .B (x1[16]), .CI
       (add_13_14_n_1365), .CO (add_13_14_n_1363), .S (acc[16]));
  ADDFXL add_13_14_g2891__5953(.A (w1[15]), .B (x1[15]), .CI
       (add_13_14_n_1367), .CO (add_13_14_n_1365), .S (acc[15]));
  ADDFXL add_13_14_g2892__5703(.A (w1[14]), .B (x1[14]), .CI
       (add_13_14_n_1369), .CO (add_13_14_n_1367), .S (acc[14]));
  ADDFXL add_13_14_g2893__7114(.A (w1[13]), .B (x1[13]), .CI
       (add_13_14_n_1371), .CO (add_13_14_n_1369), .S (acc[13]));
  ADDFXL add_13_14_g2894__5266(.A (w1[12]), .B (x1[12]), .CI
       (add_13_14_n_1373), .CO (add_13_14_n_1371), .S (acc[12]));
  ADDFXL add_13_14_g2895__2250(.A (w1[11]), .B (x1[11]), .CI
       (add_13_14_n_1375), .CO (add_13_14_n_1373), .S (acc[11]));
  ADDFXL add_13_14_g2896__6083(.A (w1[10]), .B (x1[10]), .CI
       (add_13_14_n_1377), .CO (add_13_14_n_1375), .S (acc[10]));
  ADDFXL add_13_14_g2897__2703(.A (w1[9]), .B (x1[9]), .CI
       (add_13_14_n_1379), .CO (add_13_14_n_1377), .S (acc[9]));
  ADDFXL add_13_14_g2898__5795(.A (w1[8]), .B (x1[8]), .CI
       (add_13_14_n_1381), .CO (add_13_14_n_1379), .S (acc[8]));
  ADDFXL add_13_14_g2899__7344(.A (w1[7]), .B (x1[7]), .CI
       (add_13_14_n_1383), .CO (add_13_14_n_1381), .S (acc[7]));
  ADDFXL add_13_14_g2900__1840(.A (w1[6]), .B (x1[6]), .CI
       (add_13_14_n_1385), .CO (add_13_14_n_1383), .S (acc[6]));
  ADDFXL add_13_14_g2901__5019(.A (w1[5]), .B (x1[5]), .CI
       (add_13_14_n_1387), .CO (add_13_14_n_1385), .S (acc[5]));
  ADDFXL add_13_14_g2902__1857(.A (w1[4]), .B (x1[4]), .CI
       (add_13_14_n_1389), .CO (add_13_14_n_1387), .S (acc[4]));
  ADDFXL add_13_14_g2903__9906(.A (w1[3]), .B (x1[3]), .CI
       (add_13_14_n_1391), .CO (add_13_14_n_1389), .S (acc[3]));
  ADDFXL add_13_14_g2904__8780(.A (w1[2]), .B (x1[2]), .CI
       (add_13_14_n_1393), .CO (add_13_14_n_1391), .S (acc[2]));
  ADDFXL add_13_14_g2905__4296(.A (w1[1]), .B (x1[1]), .CI
       (add_13_14_n_1395), .CO (add_13_14_n_1393), .S (acc[1]));
  AND2X1 add_13_14_g2907__3772(.A (x1[0]), .B (w1[0]), .Y
       (add_13_14_n_1395));
  XOR3XL add_13_14_g2__1474(.A (w1[31]), .B (x1[31]), .C
       (add_13_14_n_1335), .Y (acc[31]));
  XOR2XL add_13_14_g2911__4547(.A (x1[0]), .B (w1[0]), .Y (acc[0]));
endmodule

